In [1]:
print ('hello')

hello


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from '/Users/neelsheth/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>

In [5]:
ls = [[1,2,3,13] , [4,5,6,14] , [7,8,9,15] , [10,11,12,16] ]

In [6]:
ls

[[1, 2, 3, 13], [4, 5, 6, 14], [7, 8, 9, 15], [10, 11, 12, 16]]

In [7]:
type(ls)

list

## Converting list to array

In [8]:
ar = np.array(ls)

In [9]:
ar

array([[ 1,  2,  3, 13],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 15],
       [10, 11, 12, 16]])

In [10]:
type (ar) # Here, ndarray means n dimentional array

numpy.ndarray

## Checking Dimensions of an array

In [11]:
ar.ndim

2

## Checking the shape, size and datatype of the array

In [12]:
ar.shape

(4, 4)

In [13]:
ar.size

16

In [14]:
ar.dtype

dtype('int64')

## Creating array using zeros and ones

In [15]:
# There is a function named Zero which we can use : zeros(size,dtype,order)

zeros = np.zeros((3,4))

In [16]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
ones = np.ones((2,7))

In [18]:
ones

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

## Creating array of random number

In [19]:
ran = np.random.random((3,9))

In [20]:
ran

array([[4.65062637e-01, 7.76264843e-01, 7.32990672e-01, 9.00655007e-01,
        1.54702899e-01, 1.31458614e-01, 6.30847861e-01, 4.17175968e-01,
        2.52678379e-01],
       [7.20729339e-01, 6.07747354e-01, 4.62445625e-01, 8.50967137e-01,
        6.73362597e-01, 5.21033426e-01, 1.83641214e-01, 2.50167324e-01,
        9.28134518e-01],
       [3.07943410e-01, 7.45247905e-01, 9.80959950e-01, 2.24681413e-04,
        2.04941241e-01, 4.48373380e-01, 6.17681359e-01, 3.50614201e-01,
        2.78154188e-01]])

In [21]:
ran2 = np.random.rand()

In [22]:
ran2

0.15966283284957572

### random function provides numbers between 0 to 1

In [23]:
if np.random.random() > 0.5:
    print ("Run the cell")
else :
    print ("Don't run the cell")

Run the cell


In [24]:
if np.random.random() > 0.5:
    print ("Run the cell")
else :
    print ("Don't run the cell")

Run the cell


In [25]:
if np.random.random() > 0.5:
    print ("Run the cell")
else :
    print ("Don't run the cell")

Don't run the cell


## Arange function

In [26]:
np.arange (2, 11, 2)   # np.arange (start, end, difference)

array([ 2,  4,  6,  8, 10])

##### Difference between range and arange is that range is built-in function in python while arange is third party function which is Numpy

## Linespace function

### This function provides number of required values from range with the same space

In [27]:
np.linspace (1,11,10) # np.linespace (start, end, num of required values from range)

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [28]:
np.linspace (1,11,5)

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

## Reshaping the array

### np.reshape (array name, new shape, order)

In [29]:
ar = np.random.random((3,2))

In [30]:
ar

array([[0.13458461, 0.92597471],
       [0.85045896, 0.07988444],
       [0.9234447 , 0.5081185 ]])

In [31]:
np.reshape(ar, (2,3))

array([[0.13458461, 0.92597471, 0.85045896],
       [0.07988444, 0.9234447 , 0.5081185 ]])

### Important note :  While reshaping the array, initial number of elements = final number of element

## Flatten array : Converts any dimention to one dimention

In [32]:
arr = np.random.random ((4,5))

In [33]:
arr

array([[0.99834748, 0.4909379 , 0.90683092, 0.9059512 , 0.48083498],
       [0.83679881, 0.4839674 , 0.68663478, 0.50523562, 0.58223777],
       [0.06006025, 0.86629892, 0.77820782, 0.68102644, 0.90645329],
       [0.81594957, 0.7364425 , 0.29026322, 0.83627674, 0.3612712 ]])

In [34]:
arr.flatten()

array([0.99834748, 0.4909379 , 0.90683092, 0.9059512 , 0.48083498,
       0.83679881, 0.4839674 , 0.68663478, 0.50523562, 0.58223777,
       0.06006025, 0.86629892, 0.77820782, 0.68102644, 0.90645329,
       0.81594957, 0.7364425 , 0.29026322, 0.83627674, 0.3612712 ])

# Arithmetic Operations in Array

In [35]:
are = np.array([1,2,3,4,5,6])

In [36]:
are

array([1, 2, 3, 4, 5, 6])

## Addition, Subtraction, Multiplication, Division and Remainder in array

In [37]:
print (are + 1)
print (are - 5)
print (are * 7)
print (are / 2)
print (are % 2)

[2 3 4 5 6 7]
[-4 -3 -2 -1  0  1]
[ 7 14 21 28 35 42]
[0.5 1.  1.5 2.  2.5 3. ]
[1 0 1 0 1 0]


## Finding powers of elements

In [38]:
print (are ** 2)
print (are ** 3)

[ 1  4  9 16 25 36]
[  1   8  27  64 125 216]


## Max and Min in 1D array

In [39]:
are.max()

6

In [40]:
are.min()

1

## Max and Min in Multidimentional array

In [41]:
ls = [[1,2,3,13] , [4,5,6,14] , [7,8,9,15] , [10,11,12,16] ]

In [42]:
lis = np.array(ls)

In [43]:
lis

array([[ 1,  2,  3, 13],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 15],
       [10, 11, 12, 16]])

### 0 Axis means column and 1 Axis means row

In [44]:
lis.max(axis = 0)

array([10, 11, 12, 16])

In [45]:
lis.min(axis = 1)

array([ 1,  4,  7, 10])

In [46]:
lis.sum()

136

## Arithmetic operations in 2D array

In [47]:
ar1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
ar2 = np.array([[9,8,7], [6,5,4], [3,2,1]])
ar3 = np.array([[9,8,7,6], [6,5,4,3], [3,2,1,0]])

In [48]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
ar2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [50]:
ar1+ar2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

#### Arrays with different shape will not accept any operation

In [51]:
ar1+ar3

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [52]:
ar1*ar2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

### Dot product

In [53]:
ar1.dot(ar2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [54]:
ar2.dot(ar1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

### Indexing

In [55]:
arr = np.array([1,2,3,4,5])

In [56]:
arr

array([1, 2, 3, 4, 5])

In [57]:
arr[:3]

array([1, 2, 3])

In [58]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
# Slicing in 2D array

# Array_name [start : end (for rows) , start : end (for column)]

ar1[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
ar1 [ : 2 , :]

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
ar1 [ : , : 1]

array([[1],
       [4],
       [7]])

In [62]:
ar1 [1 : 2 , 1 : 2]

array([[5]])

In [63]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Sorting using Numpy

In [64]:
M = np.array ([[5,3,6,1,9] , [7,5,2,1,8] , [1,3,2,6,4]])

In [65]:
M

array([[5, 3, 6, 1, 9],
       [7, 5, 2, 1, 8],
       [1, 3, 2, 6, 4]])

In [66]:
# For sorting, we have Sort function in Numpy

# numpy.sort(array_name, axis = 0 or 1, kind = None, order = None)

# Here, default is quicksort algo., so if we don't mention kind then it'll go with quick sort

In [67]:
np.sort(M, axis = 1, kind = 'mergesort')

array([[1, 3, 5, 6, 9],
       [1, 2, 5, 7, 8],
       [1, 2, 3, 4, 6]])

In [68]:
np.sort(M, axis = 0, kind = 'mergesort')

array([[1, 3, 2, 1, 4],
       [5, 3, 2, 1, 8],
       [7, 5, 6, 6, 9]])

# Deep dive in array slicing

### For 1D array

In [69]:
arr1 = np.array ([1,3,5,7,2,4,6,8])

In [70]:
arr1

array([1, 3, 5, 7, 2, 4, 6, 8])

In [71]:
arr1[5]

4

In [72]:
arr1[-7]

3

In [73]:
arr1[1:-2]

array([3, 5, 7, 2, 4])

### For 2D array

In [74]:
arr = np.array ([[1,3,5,7] , [2,4,6,8] , [9,7,5,3] , [10,8,6,4]])

In [75]:
arr

array([[ 1,  3,  5,  7],
       [ 2,  4,  6,  8],
       [ 9,  7,  5,  3],
       [10,  8,  6,  4]])

In [76]:
# Array_name [start : end (for rows) , start : end (for column)]

In [77]:
arr [2 : 3 ,  : 2]

array([[9, 7]])

In [78]:
arr [2 : 3 , :]

array([[9, 7, 5, 3]])

In [79]:
arr [1 : ,]

array([[ 2,  4,  6,  8],
       [ 9,  7,  5,  3],
       [10,  8,  6,  4]])

# Merging Arrays

There are two ways : <br>
    1. Hstack / Vstack <br>
    Syntax = np.vstack / hstack ((array1 , array2)) <br>
    2. Concaenate <br> 
    Syntax = np.concatenate ((ar1 , ar2) , axis = 0 / 1)

In [80]:
ar1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
ar2 = np.array([[9,8,7], [6,5,4], [3,2,1]])

In [81]:
np.vstack((ar1 , ar2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [82]:
np.hstack((ar1 , ar2))

array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4],
       [7, 8, 9, 3, 2, 1]])

In [83]:
np.concatenate ((ar1 , ar2) , axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [84]:
np.concatenate ((ar1 , ar2) , axis = 1)

array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4],
       [7, 8, 9, 3, 2, 1]])

# Splitting merged array

There are two ways : <br>
    1. Hsplit / Vsplit <br>
    Syntax = np.vsplit / hsplit (array , number of split)

In [85]:
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
np.vsplit (ar1 , 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [87]:
np.hsplit (ar1 , 3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

# Automation using Numpy

In [88]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [89]:
for i in lst:
    if (i > 5):
        print (i)

6
7
8
9
10


The same thing we can do using numpy in one line only

In [90]:
ls = np.array(lst)

In [91]:
ls

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
ls>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])